### ISSUE TITLE
[1.12.2-1.9.0] Config Button doesn't do anything

### ISSUE THREAD

**Issue by kreezxil** [RobertSkalko/Mine-and-Slash#126] opened 2020-01-05 16:06 UTC
![image](https://user-images.githubusercontent.com/3880072/71782691-9a68fa80-2fa2-11ea-83e2-fb3910b54796.png)

Would be nice if it did.

@AzureDoom

**Comment by AzureDoom** [comment] 2020-01-05 22:06
I'll check this tonight.

**Comment by AzureDoom** [comment] 2020-01-05 23:43
![2020-01-05_18 23 54](https://user-images.githubusercontent.com/7415711/71787905-459da200-2feb-11ea-94c4-3783540604f8.png)
Works for me

**Comment by AzureDoom** [comment] 2020-01-05 23:46
Yeah I am unable to reproduce this @RobertSkalko

**Comment by kreezxil** [comment] 2020-01-06 00:22
client latest log: https://paste.ubuntu.com/p/nKfVB28ZzJ/ 

everytime I hit the config button this is spammed in the console:
```
[18:19:51] [Client thread/ERROR]: There was a critical issue trying to build the config GUI for mmorpg
java.lang.NumberFormatException: For input string: "1-"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_51]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_51]
	at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_51]
	at net.minecraftforge.fml.client.config.GuiConfigEntries$IntegerEntry.<init>(GuiConfigEntries.java:991) ~[GuiConfigEntries$IntegerEntry.class:?]
	at net.minecraftforge.fml.client.config.GuiConfigEntries.<init>(GuiConfigEntries.java:145) ~[GuiConfigEntries.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:217) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:191) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.config.GuiConfigEntries$CategoryEntry.buildChildScreen(GuiConfigEntries.java:1340) ~[GuiConfigEntries$CategoryEntry.class:?]
	at net.minecraftforge.fml.client.config.GuiConfigEntries$CategoryEntry.<init>(GuiConfigEntries.java:1325) ~[GuiConfigEntries$CategoryEntry.class:?]
	at net.minecraftforge.fml.client.config.GuiConfigEntries.<init>(GuiConfigEntries.java:178) ~[GuiConfigEntries.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:217) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:191) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.config.GuiConfigEntries$CategoryEntry.buildChildScreen(GuiConfigEntries.java:1340) ~[GuiConfigEntries$CategoryEntry.class:?]
	at net.minecraftforge.fml.client.config.GuiConfigEntries$CategoryEntry.<init>(GuiConfigEntries.java:1325) ~[GuiConfigEntries$CategoryEntry.class:?]
	at net.minecraftforge.fml.client.config.GuiConfigEntries.<init>(GuiConfigEntries.java:178) ~[GuiConfigEntries.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:217) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:112) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:96) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.DefaultGuiFactory.createConfigGui(DefaultGuiFactory.java:56) ~[DefaultGuiFactory.class:?]
	at net.minecraftforge.fml.client.GuiModList.actionPerformed(GuiModList.java:285) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443) [blk.class:?]
	at net.minecraftforge.fml.client.GuiModList.mouseClicked(GuiModList.java:199) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533) [blk.class:?]
	at net.minecraftforge.fml.client.GuiModList.handleMouseInput(GuiModList.java:329) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by AzureDoom** [comment] 2020-01-06 00:33
Your config has a broken value. This is something not added by default.

**Comment by RobertSkalko** [comment] 2020-01-06 08:13
closing, please delete the config file and let a new one generate, you can then manually edit it again. If it breaks again, try load it after each value is changed to see what's causing it.

**Closed by RobertSkalko** 2020-01-06 08:13 UTC
