### ISSUE TITLE
[1.12.2] Dupe bug - Master bag

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Mine-and-Slash#42] opened 2019-07-10 04:25 UTC
Mine and Slash-1.14.3-2.0.23

When a user makes two master bags, he can see the same inventory in both bags.

When he hands the second bag to another player, that player can throw everything out of that bag and it both throw out the items duping everything in the bag.

**Comment by ProsperCraft** [comment] 2019-07-10 04:27
Also another issue- another player made a master bag, and he sees the same things at the first player that made one.

**Comment by RobertSkalko** [comment] 2019-07-10 06:33
this only works on master bags? not other bags?

**Comment by RobertSkalko** [comment] 2019-07-10 06:46
I think i reproduced the dupe. now just to figure out how to solve it.

**Comment by RobertSkalko** [comment] 2019-07-10 07:12
well i pushed an update that fix one way to dupe hopefully. But i still can't reproduce having 2 bags share an inventory.

**Comment by RobertSkalko** [comment] 2019-07-10 16:00
Mair helped me reproduce another dupe. still baffled by it, trying to fix it now.

**Comment by RobertSkalko** [comment] 2019-07-11 07:38
fix pushed out, please try and report

**Comment by RobertSkalko** [comment] 2019-07-12 08:01
As i haven't been able to reproduce the dupe and no1 else told me anymore about it. I'll assume it was fixed by the update. If there's a new dupe please open another issue.

**Closed by RobertSkalko** 2019-07-12 08:01 UTC
