### ISSUE TITLE
Mine and Slash is re-registering already registered enchantments.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [RobertSkalko/Mine-and-Slash#63] opened 2019-08-11 01:03 UTC
Please remove this method call.  It does nothing but break things. https://github.com/RobertSkalko/Mine-and-Slash/blob/1.14.4/src/main/java/com/robertx22/mine_and_slash/mmorpg/registers/common/EnchantRegisters.java#L32
You cannot re-register already registered enchantments.

**Comment by TheRealM18** [comment] 2019-08-11 02:03
https://prnt.sc/or3vf7

**Comment by TheRealM18** [comment] 2019-08-11 02:18
Shawdow-of-Fire that is a for loop. That registers enchantments to his weapons, not registers twice.

**Comment by Shadows-of-Fire** [comment] 2019-08-11 02:20
No, its an iteration over the entire enchantment registry.  It's registering enchantments already in the registry.

**Comment by TheRealM18** [comment] 2019-08-11 02:26
Shadows-of-Fire this is not a normal weapon.  these weapons are made like trying to enchant a stick.  understand, I might not know much code, but i know what a for loop does.

**Comment by TheRealM18** [comment] 2019-08-11 02:29
Shawdow-of-Fire if you know how to read bug reports you would see this.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/10/19 6:48 PM
Description: Initializing game

java.lang.NullPointerException: null key in entry: null=10
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:73) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:120) ~[guava-21.0.jar:?] {}
	at shadows.ench.objects.ItemHellBookshelf.func_150895_a(ItemHellBookshelf.java:47) ~[?:2.0.4] {}

**Comment by Shadows-of-Fire** [comment] 2019-08-11 02:37
Which is caused by an exception thrown further up by mine and slash, as shown in the debug.log

**Comment by TheRealM18** [comment] 2019-08-11 02:43
Shadows-of-Fire you have a core mod that transforms the enchantment protocol. Mine and Slash does not do that.

**Comment by RobertSkalko** [comment] 2019-08-11 07:55
This is not a bug. This is a limitation of forge. I have already made an issue with a suggestion to fix this problem but nothing was done. take it with forge.

All my mod does is change it so my items can also get certain enchants. I do it by re-registering a few vanilla ones. 

https://github.com/MinecraftForge/MinecraftForge/issues/5929#issuecomment-513304912

I'll keep the workaround until i find a better workaround, or if forge implements some solution.

**Comment by RobertSkalko** [comment] 2019-08-11 11:24
Ok after a bit of chat in discord it seems we had a missunderstanding. That line of code is actually not needed and it was probably a leftover from my earlier workaround.

I'll make an update soon and then close this issue.

**Comment by RobertSkalko** [comment] 2019-08-11 11:38
should be fixed in latest update

**Closed by RobertSkalko** 2019-08-11 11:38 UTC
